#application.yml

instance:
    clientUrl: https://labs.kadaster.nl/fairdatapoint
    persistentUrl: https://purl.org/fairdatapoint/example
    # (!) Change secret to some random value if you are running in production environment (due to security)
    # serviceToken: <dsw-secret>
    secret: b7zFNUhFYIFLmDSFKFkp0Bnp8Z3uWGnH
    # (!) Change serviceToken to some random value if you are running in production environment (due to security)
    # serviceToken: <dsw-service-token>
    serviceToken: NlQSNbGvh7EtcpinGnHE9g91

security:
    jwt:
        token:
            # (!) Change secret to some random 128 characters string if you are running in production environment (due to security)
            # serviceToken: <fdp-secret>
            secret-key: 3fWWqp56mWjUmRHKn2v49gqdMwGFQASJDFvRSoL4aVMnAjXNahF9nVaYfEtV4bsvENdmZMf0xRbYZWBZ17YdQX1WriFkhYFMzGWpj1dGHesw0SlSP7TtUKfcSJmXxPzU

repository:
    type: 6
    triplydb:
        url: <url>
        username:
        password: